# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_create', models.TimeField(auto_now=True)),
                ('date_execute', models.TimeField(blank=True)),
                ('date_plan_execute', models.TimeField(blank=True)),
                ('priority', models.IntegerField(blank=True)),
                ('parent_task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks_manage.Tasks')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks_manage.File_storage')),
            ],
        ),
    ]
