# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
