# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manage', '0002_auto_20160312_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_manage.Task'),
        ),
    ]
