# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks_manage', '0003_auto_20160312_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks_manage.File_storage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks_manage.Status'),
        ),
    ]
