# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manage', '0004_auto_20160312_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_manage.File_storage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_manage.Task'),
        ),
    ]
