# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks_manage', '0005_auto_20160312_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks_manage.Status'),
        ),
    ]
