# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks_manage', '0008_auto_20160312_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file_storage',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='file_storage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks_manage.Task'),
        ),
        migrations.AddField(
            model_name='status',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks_manage.Task'),
        ),
    ]
