# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_manage', '0009_auto_20160316_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='satus',
            field=models.CharField(choices=[('done', 'Done'), ('Start', 'Start')], default='start', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
